import os
import re


class DMDConverter:

    def __init__(self):
        self.reset()

    def reset(self):
        self.vertices = []
        self.faces = []
        self.uv = []
        self.uv_faces = []
        self.invalid_faces_count = 0

    def analyze(self, dmd_file):
        """Режим диагностики DMD файла перед конвертацией"""
        self.reset()
        self.read_dmd(dmd_file)

        max_idx = 0
        if self.faces:
            max_idx = max(max(f) for f in self.faces)

        return {
            "vertices": len(self.vertices),
            "uvs": len(self.uv),
            "faces": len(self.faces),
            "invalid_faces": self.invalid_faces_count,
            "max_index": max_idx
        }

    def convert(self, dmd_file, output_folder, new_name=None, custom_texture=None):
        self.reset()
        self.read_dmd(dmd_file)

        if new_name and new_name.strip():
            base_name = new_name.strip()
        else:
            base_name = os.path.splitext(os.path.basename(dmd_file))[0]

        obj_path = os.path.join(output_folder, base_name + ".obj")
        mtl_path = os.path.join(output_folder, base_name + ".mtl")

        # Если передана кастомная текстура, используем её, иначе <имя_файла>.png
        if custom_texture and custom_texture.strip():
            texture_filename = os.path.basename(custom_texture.strip())
        else:
            texture_filename = base_name + ".png"

        self.write_mtl(mtl_path, texture_filename)
        self.write_obj(obj_path, base_name + ".mtl")

        max_idx = max(max(f) for f in self.faces) if self.faces else 0

        return {
            "vertices": len(self.vertices),
            "uvs": len(self.uv),
            "faces": len(self.faces),
            "invalid_faces": self.invalid_faces_count,
            "max_index": max_idx,
            "obj": obj_path,
            "mtl": mtl_path
        }

    def read_dmd(self, filename):
        mode = ""
        self.invalid_faces_count = 0

        with open(filename, "r", encoding="utf-8", errors="ignore") as f:
            for raw in f:
                line = raw.strip()
                if not line:
                    continue

                lower = line.lower()

                if "mesh vertices" in lower:
                    mode = "verts"
                    continue
                if "mesh faces" in lower:
                    mode = "faces"
                    continue
                if "texture vertices" in lower:
                    mode = "uv"
                    continue
                if "texture faces" in lower:
                    mode = "uvfaces"
                    continue

                # Вершины
                if mode == "verts":
                    nums = re.findall(r"-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?", line)
                    if len(nums) >= 3:
                        self.vertices.append((float(nums[0]), float(nums[1]), float(nums[2])))
                    continue

                # Грани + Проверка
                if mode == "faces":
                    nums = re.findall(r"\d+", line)
                    if len(nums) >= 3:
                        f1, f2, f3 = int(nums[0]), int(nums[1]), int(nums[2])
                        if f1 == f2 == f3:
                            self.invalid_faces_count += 1
                        else:
                            self.faces.append((f1, f2, f3))
                    continue

                # UV-координаты
                if mode == "uv":
                    nums = re.findall(r"-?\d+(?:\.\d+)?(?:[eE][+-]?\d+)?", line)
                    if len(nums) >= 2:
                        self.uv.append((float(nums[0]), 1.0 - float(nums[1])))
                    continue

                # UV-грани
                if mode == "uvfaces":
                    nums = re.findall(r"\d+", line)
                    if len(nums) >= 3:
                        self.uv_faces.append((int(nums[0]), int(nums[1]), int(nums[2])))
                    continue

        # Валидация граней относительно прочитанных вершин
        num_verts = len(self.vertices)
        valid_faces = []
        for f in self.faces:
            if f[0] <= num_verts and f[1] <= num_verts and f[2] <= num_verts and min(f) >= 1:
                valid_faces.append(f)
            else:
                self.invalid_faces_count += 1
        self.faces = valid_faces

    def write_mtl(self, mtl_filename, png_filename):
        with open(mtl_filename, "w", encoding="utf-8") as mtl:
            mtl.write("# Generated by DMDConverter\n")
            mtl.write("newmtl material_0\n")
            mtl.write("Ka 1.000 1.000 1.000\n")
            mtl.write("Kd 1.000 1.000 1.000\n")
            mtl.write("Ks 0.000 0.000 0.000\n")
            mtl.write(f"map_Kd {png_filename}\n")

    def write_obj(self, filename, mtl_name):
        with open(filename, "w", encoding="utf-8") as obj:
            obj.write("# Generated by DMDConverter\n")
            obj.write(f"mtllib {mtl_name}\n")
            obj.write("usemtl material_0\n\n")

            for x, y, z in self.vertices:
                obj.write(f"v {x} {y} {z}\n")

            obj.write("\n")

            for u, v in self.uv:
                obj.write(f"vt {u} {v}\n")

            obj.write("\n")

            has_uv = len(self.uv_faces) == len(self.faces) and len(self.uv) > 0

            if has_uv:
                for face, uv in zip(self.faces, self.uv_faces):
                    obj.write(f"f {face[0]}/{uv[0]} {face[1]}/{uv[1]} {face[2]}/{uv[2]}\n")
            else:
                for face in self.faces:
                    obj.write(f"f {face[0]} {face[1]} {face[2]}\n")
